host_project_id    = "theta-signal-418711"
service_project_id = "ornate-node-483516-e3"
network_name       = "shared-vpc-hands-on"
subnet_region      = "asia-south1"
subnet_cidr        = "10.2.0.0/24"
vm_name            = "shared-vpc-test-vm"
machine_type       = "e2-small"
boot_image         = "debian-cloud/debian-11"